[project]
name = "data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.8",
    "g4f>=0.4.6.0",
    "jinja2>=3.1.5",
    "uvicorn>=0.34.0",
]
